# Utiliza una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo en /usr/src/app
WORKDIR /usr/src/app

# Copia los archivos del proyecto (asegúrate de tener un archivo .dockerignore para excluir los archivos no deseados)
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el código fuente de la aplicación
COPY . .

# Compila TypeScript
RUN npm run build

# Expone el puerto en el que la aplicación va a escuchar
EXPOSE 3000

# Comando para ejecutar la aplicación cuando el contenedor se inicie
CMD ["npm", "start"]
