# Use Alpine Linux as a parent image
FROM alpine:3.18.4

# Instalar Python y otras dependencias
RUN apk --no-cache add python3-dev=3.2.0

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de la aplicación a la imagen
COPY . /app

# Actualizar pip
RUN pip install --upgrade pip

# Instalar las dependencias de la aplicación
RUN pip install -r requirements.txt

# Exponer el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5000

# Iniciar la aplicación Flask cuando se inicie el contenedor
CMD ["python", "app.py"]
