# Utiliza una imagen base de Alpine Linux
FROM alpine:latest

# Instala Python y otras dependencias
RUN apk update && \
    apk add --no-cache python3 && \
    apk add --no-cache py3-pip

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de la aplicación a la imagen
COPY . /app

# Actualiza pip y luego instala las dependencias de la aplicación
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install flask[async]
RUN pip install flask_cors
RUN pip install openai
RUN pip install chromadb

# Expone el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5000

# Inicia la aplicación Flask cuando se inicia el contenedor
CMD ["python", "app.py"]
